# Generated by Django 5.0.6 on 2024-06-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='album',
        ),
    ]
