# Generated by Django 5.0.6 on 2024-06-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
